<a href="https://colab.research.google.com/github/metalnom/Colab_01/blob/master/note03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CNN

# img2col 구현

In [0]:
import numpy as np

def im2col(image, flt_h, flt_w, out_h, out_w):
  img_h, img_w = image.shape

  cols = np.zeros((flt_h*flt_w, out_h*out_w))

  for h in range(out_h):
    h_lim = h + flt_h
    for w in range(out_w):
      w_lim = w + flt_w
      cols[:, h*out_w + w] = image[h:h_lim, w:w_lim].reshape(-1)

  return cols

In [4]:
img = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16]])
cols = im2col(img, 2, 2, 3, 3)
print(cols)

[[ 1.  2.  3.  5.  6.  7.  9. 10. 11.]
 [ 2.  3.  4.  6.  7.  8. 10. 11. 12.]
 [ 5.  6.  7.  9. 10. 11. 13. 14. 15.]
 [ 6.  7.  8. 10. 11. 12. 14. 15. 16.]]


In [0]:
# 배열 접근을 줄여 속도 향상

import numpy as np

def im2col(image, flt_h, flt_w, out_h, out_w):
  img_h, img_w = image.shape
  cols = np.zeros((flt_h, flt_w, out_h, out_w))

  for h in range(flt_h):
    h_lim = h + out_h
    for w in range(flt_w):
      w_lim = w + out_w
      cols[h, w, :, :] = image[h:h_lim, w:w_lim]
  
  cols = cols.reshape(flt_h*flt_w, out_h*out_w)

  return cols

In [6]:
cols = im2col(img, 2, 2, 3, 3)
print(cols)

[[ 1.  2.  3.  5.  6.  7.  9. 10. 11.]
 [ 2.  3.  4.  6.  7.  8. 10. 11. 12.]
 [ 5.  6.  7.  9. 10. 11. 13. 14. 15.]
 [ 6.  7.  8. 10. 11. 12. 14. 15. 16.]]


![대체 텍스트](https://drive.google.com/uc?id=1BnfOIre_bhgSq9KHAI-sW8oUmdQ_EIvK)